name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      REACT_APP_API_URL: https://shredtest.coderadiant.com/
      REACT_APP_APP_ENV: PROD
      REACT_APP_GOOGLE_LOGIN_AUTH_URL: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&scope=openid%20profile%20email&response_type=code&client_id=487563935567-9d7hunscovdvc8940lgfm10ak3ilpiui.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fshredtest.coderadiant.com%2Fgsign%2Fgoogle-login
      REACT_APP_GMAIL_SEND_AUTH_URL: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fgmail.send&response_type=code&client_id=487563935567-doi10pjcfdikmfh8vioob7qnm1on9hbu.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fshredtest.coderadiant.com%2Finvite%2FsetupMailer
      REACT_APP_PEERJS_URL: https://shredtest.coderadiant.com/
      REACT_APP_PEERJS_PORT: 443

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies with Yarn
        run: yarn install

      - name: Build React app with Yarn
        run: yarn build

      - name: Transfer build folder to EC2
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: ./build/
          target: /tmp/react-build/

      - name: Move build into place on EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo rm -rf /var/www/exam-portal-backend/public
            sudo mkdir -p /var/www/exam-portal-backend/public
            sudo mv /tmp/react-build/build/* /var/www/exam-portal-backend/public
            sudo mv /var/www/exam-portal-backend/public/index.html /var/www/exam-portal-backend/index.html
