name: Deploy React App to CloudFront

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build
        env:
          VITE_API_URL: https://api.shredtest.scriptbliss.com
          VITE_APP_ENV: PROD
          VITE_GOOGLE_LOGIN_AUTH_URL: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&scope=openid%20profile%20email&response_type=code&client_id=487563935567-9d7hunscovdvc8940lgfm10ak3ilpiui.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fshredtest.scriptbliss.com%2Fgsign%2Fgoogle-login
          VITE_GMAIL_SEND_AUTH_URL: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fgmail.send&response_type=code&client_id=487563935567-doi10pjcfdikmfh8vioob7qnm1on9hbu.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fshredtest.scriptbliss.com%2Finvite%2FsetupMailer
          VITE_PEERJS_URL: https://shredtest.scriptbliss.com
          VITE_PEERJS_PORT: 443

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync to S3
        run: |
          aws s3 sync dist/ s3://${{ secrets.S3_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
